server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://localhost:5432/SOAdb
    username: postgres
    password: code4code
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgrSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

